name: "Hello World"

on: push

jobs:
    hello-job:
        env:
            WORD : "Canada"
        runs-on: ubuntu-latest
        steps:
        - name: Echo text
          run: echo "Hello, $WORD!"
